# Generated by Django 5.0.4 on 2024-04-07 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Woman',
            new_name='Women',
        ),
    ]
